"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {api,type Invitation} from "@/lib/identity-api";
import {IdentityShell} from "./identity-shell";
import {useAccount} from "./use-account";
import {SearchForm} from "./marketplace";
export function PersonalSpace({section="overview"}:{section?:string}){
 const {user,error,retry}=useAccount(); const [invitations,setInvitations]=useState<Invitation[]>();const [inviteError,setInviteError]=useState("");
 useEffect(()=>{if(!user)return;sessionStorage.setItem(`fieldops:context:${user.id}`,"personal");const controller=new AbortController();api<Invitation[]>("invitations",{signal:controller.signal}).then(setInvitations).catch(()=>{if(!controller.signal.aborted)setInviteError("Invitations could not be loaded.");});return()=>controller.abort();},[user]);
 return <IdentityShell signedIn>{error?<div className="error" role="alert">{error}<button className="secondary small" onClick={retry}>Retry</button></div>:!user?<p role="status">Loading your personal space…</p>:<div className="workspace-layout"><aside className="workspace-sidebar"><span className="workspace-label">Personal space</span><nav aria-label="Personal"><Link aria-current={section==="overview"?"page":undefined} href="/my">Overview</Link><Link href="/services">Find services</Link><Link aria-current={section==="requests"?"page":undefined} href="/my/requests">My requests</Link><Link aria-current={section==="account"?"page":undefined} href="/my/account">Account</Link></nav><div className="sidebar-bottom"><Link href="/select-business">Your businesses</Link><Link href="/create-business">Create business</Link>{user.platformAdmin&&<Link href="/platform">Platform administration</Link>}</div></aside><div className="workspace-content"><div className="dashboard-heading"><p className="kicker">Your personal space</p><h1>{section==="account"?"Your account":section==="requests"?"Your service requests":`Hello, ${user.displayName.split(" ")[0]}.`}</h1><p>{section==="account"?"One identity for your personal life and your teams.":"A little help, right where you need it."}</p></div>{section==="account"?<section className="panel"><h2>Account details</h2><dl><dt>Name</dt><dd>{user.displayName}</dd><dt>Email address</dt><dd>{user.email}</dd><dt>Email status</dt><dd>Verified</dd></dl><p className="hint mt-6">Profile editing and password recovery are not available yet.</p></section>:<><SearchForm/><section className="panel unavailable"><span className="badge">Coming next</span><h2>{section==="requests"?"Your requests, all in one place.":"From the first request to the final fix."}</h2><p>Live service requests and appointment tracking are not available yet. Explore the sample experience to see how they will work.</p><Link className="button secondary" href="/preview/customer">Preview with sample data</Link></section><div className="dashboard-columns"><section className="panel"><h2>Your invitations</h2>{inviteError?<p role="alert" className="error">{inviteError} <Link href="/invitations">Try the invitation inbox</Link></p>:invitations===undefined?<p role="status">Loading invitations…</p>:invitations.length?<><p>{invitations.length} pending {invitations.length===1?"invitation":"invitations"} to join a team.</p><Link className="text-link" href="/invitations">Review invitations</Link></>:<p>No pending invitations. A business owner can invite you using your account email.</p>}</section><section className="panel"><h2>Have a business of your own?</h2><p>Set it up with this account. Keep your personal requests and business workspaces separate.</p><Link className="text-link" href="/create-business">Create business</Link></section></div></>}</div></div>}</IdentityShell>;
}
