"use client";
import Link from "next/link";
import {useEffect,useState,type FormEvent} from "react";
import {providers} from "@/lib/marketplace-samples";
import {setIntent} from "@/lib/identity-api";
import {IdentityShell} from "./identity-shell";
import {useAccount} from "./use-account";
export function RequestPreview({slug}:{slug:string}){
 const provider=providers.find(p=>p.slug===slug)??providers[0];
 // Store only a non-secret provider slug before the account guard may redirect.
 useEffect(()=>{setIntent(`request-preview:${provider.slug}`);},[provider.slug]);
 const {user,error,retry}=useAccount();const [step,setStep]=useState(1);const [data,setData]=useState<Record<string,string>>({service:provider.services[0],issue:"",address:"",date:"",window:"Morning"});
 function review(e:FormEvent<HTMLFormElement>){e.preventDefault();setStep(2);}
 return <IdentityShell signedIn>{error?<p className="error" role="alert">{error}<button onClick={retry}>Retry</button></p>:!user?<p role="status">Loading your account…</p>:<div className="request-layout"><Link href={`/services/${provider.slug}`}>Back to {provider.name}</Link><div className="page-heading"><p className="kicker">Service request preview</p><h1>{step===3?"You’ve reached the end of the preview.":"Tell us about the work."}</h1><p>Sample provider: {provider.name}. Use example details only. Nothing is sent or saved.</p></div><ol className="progress-steps" aria-label="Request steps"><li aria-current={step===1?"step":undefined}>1. Details</li><li aria-current={step===2?"step":undefined}>2. Review</li><li aria-current={step===3?"step":undefined}>3. Finish</li></ol>{step===1?<form className="panel stack" onSubmit={review}><label>Service<select value={data.service} onChange={e=>setData({...data,service:e.target.value})}>{provider.services.map(s=><option key={s}>{s}</option>)}</select></label><label>What needs attention?<textarea required maxLength={1000} placeholder="Example: the kitchen tap has a persistent drip" value={data.issue} onChange={e=>setData({...data,issue:e.target.value})}/></label><label>Example service address<input required maxLength={200} placeholder="12 Example Lane" value={data.address} onChange={e=>setData({...data,address:e.target.value})}/></label><div className="form-columns"><label>Preferred date<input required type="date" value={data.date} onChange={e=>setData({...data,date:e.target.value})}/></label><label>Preferred window<select value={data.window} onChange={e=>setData({...data,window:e.target.value})}><option>Morning</option><option>Afternoon</option><option>Flexible</option></select></label></div><p className="hint">A preferred time is a request, not a confirmed appointment.</p><button>Review sample request</button></form>:step===2?<section className="panel stack"><h2>Review your sample request</h2><dl>{Object.entries(data).map(([k,v])=><div key={k}><dt>{({service:"Service",issue:"Issue",address:"Example address",date:"Preferred date",window:"Preferred window"} as Record<string,string>)[k]}</dt><dd>{v}</dd></div>)}</dl><p>This preview does not contact {provider.name} or book a visit.</p><div className="actions"><button className="secondary" onClick={()=>setStep(1)}>Edit details</button><button onClick={()=>{setData({});setStep(3);sessionStorage.removeItem("fieldops:intent");}}>Finish preview</button></div></section>:<section className="panel stack"><h2 role="status">Preview complete — no request was sent.</h2><p>Your sample details have been cleared. You can keep exploring services or return to your personal space.</p><Link className="button" href="/my">Back to personal space</Link></section>}</div>}</IdentityShell>;
}
